Final/Models/CompanyName_tbl.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyName_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyName_tbl()
        {
            this.CountryCompanyName_tbl = new HashSet<CountryCompanyName_tbl>();
        }
    
        public int companyID { get; set; }
        public string companyName { get; set; }
        public string shortCode { get; set; }
        public string corpInfo { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> countryID { get; set; }
        public string exchangeCodeID { get; set; }
        public Nullable<int> companyTypeID { get; set; }
        public Nullable<int> businessSectorID { get; set; }
    
        public virtual BusinessSector_tbl BusinessSector_tbl { get; set; }
        public virtual CompanyType_tbl CompanyType_tbl { get; set; }
        public virtual Exchange_tbl Exchange_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryCompanyName_tbl> CountryCompanyName_tbl { get; set; }
    }
}

Final/Controllers/CompanyName_tblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final.Models;

namespace Final.Controllers
{
    public class CompanyName_tblController : Controller
    {
        private CompanyCaptureDBEntities1 db = new CompanyCaptureDBEntities1();

        // GET: CompanyName_tbl
        public ActionResult Index()
        {


            var companyName_tbl = db.CompanyName_tbl.Include(c => c.BusinessSector_tbl).Include(c => c.CompanyType_tbl).Include(c => c.Exchange_tbl).Include(c => c.CountryCompanyName_tbl);
            return View(companyName_tbl.ToList());
        }

        //GET: CompanyName_tbl populate Table view
        public ActionResult Search(string searchBy, string list)
        {

  ///////////////////////////////////////////////////////////////   Drop down population                 /////////////////////////////////////////////////

            var ola = new object[] { "Exchange", "Business Sector", "Country", "Company Name" };
            ViewBag.list = new SelectList(ola);

 //////////////////////////////////////////  Creating a Query for Company Name //////////////////////////////////////////////////////////////////////////
//            var comList = new List<string>();
//            var comQuery = from com in db.CompanyName_tbl
//                           select com.companyName;
//            comList.AddRange(comQuery.Distinct());

//            /////////////////////////////  Creating a Query for Exchange Name ///////////////////////////////
//            var exList = new List<string>();
//            var exQuery = from ex in db.Exchange_tbl
//                           select ex.exchangeCodeID;
//            exList.AddRange(exQuery.Distinct());

//            /////////////////////////////  Creating a Query for country Name ///////////////////////////////
//            var couList = new List<string>();
//            var couQuery = from cou in db.Country_tbl
//                           select cou.countryName;
//            couList.AddRange(couQuery.Distinct());

//            /////////////////////////////  Creating a Query for Business Sector Name ///////////////////////////////
//            var busList = new List<string>();
//            var busQuery = from bus in db.BusinessSector_tbl
//                           select bus.businessSectorDesc;
//            busList.AddRange(busQuery.Distinct());

/////////////////////////////////////////////////////////   Creating a list of all queried Com name     //////////////////////////////////////////////////////////

//            IList<CompanyName_tbl> comNameList = new List<CompanyName_tbl>();
//            var co = from k in db.CompanyName_tbl select k;

//            IList<Country_tbl> couNameList = new List<Country_tbl>();
//            var c = from g in db.Country_tbl select g;


//            IList<Exchange_tbl> exNameList = new List<Exchange_tbl>();
//            var e = from f in db.Exchange_tbl select f;

//            IList<BusinessSector_tbl> BusNameList = new List<BusinessSector_tbl>();
//            var b = from r in db.BusinessSector_tbl select r;


//////////////////////////////////////////////////  ViewBags   /////////////////////////////////////////////////////////////////////////////////////


            ViewBag.companyNameID = new SelectList(db.CompanyName_tbl, "companyID", "companyName");
            ViewBag.businessSectorID = new SelectList(db.BusinessSector_tbl, "businessSectorID", "businessSectorDesc");
            ViewBag.companyTypeID = new SelectList(db.CompanyType_tbl, "companyTypeID", "companyTypeDesc");
            ViewBag.exchangeCodeID = new SelectList(db.Exchange_tbl, "exchangeCodeID", "exchangeName");

            //////////////////////////////////////////////////////////////


            var comName = from g in db.CompanyName_tbl
                          select g;

            if (!String.IsNullOrEmpty(searchBy))
            {


                if (list.Equals("Company Name"))
                {


                    comName = comName.Where(s => s.companyName.Contains(searchBy));
                }
               


                if (list.Equals("Exchange"))
                {

                    comName = comName.Where(s => s.exchangeCodeID.Contains(searchBy));
                }
                


                if (list.Equals("Business Sector"))
                {

                    comName = comName.Where(s => s.BusinessSector_tbl.businessSectorDesc.Contains(searchBy));
                }
                if (list.Equals("Country"))
                {

                    comName = comName.Where(s => s.countryID.ToString().Contains(searchBy));
                }

            }
            else 
            {
                return View(comName.ToList());
            }
            return View(comName);

        }

        // GET: CompanyName_tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyName_tbl companyName_tbl = db.CompanyName_tbl.Find(id);
            if (companyName_tbl == null)
            {
                return HttpNotFound();
            }
            return View(companyName_tbl);
        }
       

        // GET: CompanyName_tbl/Create
        public ActionResult Create()
        {
            //var comList = new List<string>();
            //var comQuery = from com in db.CompanyName_tbl
            //                  select com.companyName;
            //comList.AddRange(comQuery.Distinct());

            ///////////////////////////////////////////////////////////////

            //IList<CompanyName_tbl> comNameList = new List<CompanyName_tbl>();
            //var co = from k in db.CompanyName_tbl select k;

            ////////////////////////////////////////////////////////////

            //var li = new object[] { "Exchange", "Business Sector", "Country", "Company Name" };

            //ViewBag.list = new SelectList(li);

            ////////////////////////////////////////////////////////////////

            //if (!String.IsNullOrEmpty(searchBy))
            //{
            //    co = co.Where(s => s.companyName.Contains(searchBy));
            //}

            //var requiredList = co.ToList();


            //if (li.Equals("Company Name"))
            //{
            //    if (!String.IsNullOrEmpty(searchBy))
            //    {

            //        return View(co = co.Where(s => s.companyName.Contains(searchBy)));
            //    }
            //}
            ////if (li.Equals("Country"))
            ////{
            ////    if (!String.IsNullOrEmpty(searchBy))
            ////    {

            ////        return View(db.CompanyName_tbl.Where(s => s.countryID == searchBy || searchBy == null).ToList());
            ////    }
            ////}
            //if (li.Equals("Exchange"))
            //{
            //    if (!String.IsNullOrEmpty(searchBy))
            //    {
            //        return View(db.CompanyName_tbl.Where(s => s.exchangeCodeID == searchBy || searchBy == null).ToList());
            //    }
            //}
            //if (li.Equals("Business Sector"))
            //{
            //    if (!String.IsNullOrEmpty(searchBy))
            //    {
            //        return View(db.BusinessSector_tbl.Where(s => s.businessSectorDesc == searchBy || searchBy == null).ToList());
            //    }
            //}
            return View();


        }

        // POST: CompanyName_tbl/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "companyID,companyName,shortCode,corpInfo,updateDate,countryID,exchangeCodeID,companyTypeID,businessSectorID")] CompanyName_tbl companyName_tbl)
        {
            if (ModelState.IsValid)
            {
                db.CompanyName_tbl.Add(companyName_tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.companyNameID = new SelectList(db.CompanyName_tbl, "companyID", "companyName","shortCode","corpInfo", companyName_tbl.companyName);
            ViewBag.businessSectorID = new SelectList(db.BusinessSector_tbl, "businessSectorID", "businessSectorDesc", companyName_tbl.businessSectorID);
            ViewBag.companyTypeID = new SelectList(db.CompanyType_tbl, "companyTypeID", "companyTypeDesc", companyName_tbl.companyTypeID);
            ViewBag.exchangeCodeID = new SelectList(db.Exchange_tbl, "exchangeCodeID", "exchangeName", companyName_tbl.exchangeCodeID);
            return View(companyName_tbl);
        }

        // GET: CompanyName_tbl/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyName_tbl companyName_tbl = db.CompanyName_tbl.Find(id);
            if (companyName_tbl == null)
            {
                return HttpNotFound();
            }
            ViewBag.businessSectorID = new SelectList(db.BusinessSector_tbl, "businessSectorID", "businessSectorDesc", companyName_tbl.businessSectorID);
            ViewBag.companyTypeID = new SelectList(db.CompanyType_tbl, "companyTypeID", "companyTypeDesc", companyName_tbl.companyTypeID);
            ViewBag.exchangeCodeID = new SelectList(db.Exchange_tbl, "exchangeCodeID", "exchangeName", companyName_tbl.exchangeCodeID);
            return View(companyName_tbl);
        }

        // POST: CompanyName_tbl/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

Final/Views/CompanyName_tbl/Index.cshtml
@model IEnumerable<Final.Models.CompanyName_tbl>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@using (Html.BeginForm())
{
    @Html.DropDownList("list2")
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.companyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.shortCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.corpInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.updateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.countryID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessSector_tbl.businessSectorDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyType_tbl.companyTypeDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Exchange_tbl.exchangeName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.companyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.shortCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.corpInfo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.updateDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.countryID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BusinessSector_tbl.businessSectorDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyType_tbl.companyTypeDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Exchange_tbl.exchangeName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.companyID }) |
            @Html.ActionLink("Details", "Details", new { id=item.companyID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.companyID })
        </td>
    </tr>
}

</table>

Final/Views/CompanyName_tbl/Search.cshtml
@model IEnumerable<Final.Models.CompanyName_tbl> 
@{
    ViewBag.Title = "Search";
}

<html>
<head>
    <style>
        fieldset {
            padding: 1em;
            font: 100%/1 Arial;
            /*border:2px solid green;*/
            border: 2px solid grey;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("tr[id=popover]").popover({ placement: "top", trigger: "click" });
        });

    </script>


</head>



<body>


    <br />
    <br />
    <br />
    <div class="row">
        <div class="col-md-7">

        </div>
    </div>

    <form class="form-horizontal" style="background-color:lightgray">


        <div class="row">
            <div class="col-md-12 col-md-offset-0">
                <fieldset>
                    <legend>
                        <a href="#" class="btn btn-primary btn-lg btn-block" style="background-color:#010431;">Search</a>
                    </legend>
                    @using (Html.BeginForm())
                    {
                        <div class="form-inline form-group">
                            <div class="col-md-8 col-md-offset-0">
                                <label for="label" class="col-sm-1 col-sm-offset-0 control-label">Type</label>
                                <div class="col-md-12 col-md-offset-2">
                                    <div class="form-group">

                                        <div class="col-md-10 ">
                                            @Html.DropDownList("list")

                                        </div>
                                    </div>&nbsp;<input id="btn btn-primary" type="submit" value="Search" />
                                </div>
                            </div>
                        </div>


                        <div class="form-group ">
                            <div class="col-md-8 col-md-offset-0">
                                <label for="label" class="col-sm-1 col-sm-offset-0 control-label">Name</label>
                                <div class="col-md-12 col-md-offset-2">
                                    @Html.TextBox("searchBy")
                                </div>
                            </div>
                        </div>
                        <br />
                        <br />
                        <br />

                        <div class="container">
                            <div class="col-md-10 col-md-offset-1">
                                <div id="myPopoverContent">
                                    <table class="table table-hover">
                                       
                                                    @if (Model.Count() > 0)
                                                    {

                                                        foreach (var item in Model)
                                                        {
                                                            <tr id="popover" title="Company Information" data-content="@Html.DisplayFor(modelItem => item.Exchange_tbl.exchangeName)
                                         @Html.DisplayFor(modelItem => item.CompanyType_tbl.companyTypeDesc)
                                        @Html.DisplayFor(modelItem => item.BusinessSector_tbl.businessSectorDesc)
                                        @Html.DisplayFor(modelItem => item.countryID)">
>

                                                                <td>
                                                                    @Html.DisplayFor(modelItem => item.companyName)
                                                                </td>


                                                                <td>
                                                                    @Html.DisplayFor(modelItem => item.exchangeCodeID)
                                                                </td>

                                                            </tr>
                                                        }
                                                    }
                                                    else
                                                    {

                                                        <tr>
                                                            <td align="center"><b>No Records found</b></td>

                                                        </tr>

                                                    }


                                    </table>
                                </div>
                            </div>
                        </div>
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                       

                    }
                    @using (Html.BeginForm("Create", "CompanyName_tbl", FormMethod.Get))
                    {

                        <div class="form-inline form-group">
                            <div class="col-md-10 col-md-offset-2">
                                <button class="btn btn-default" type="submit" id="addBtn" style="width:100px; height:34px;" onclick="location.href='@Url.Action("Add", "Function")'">Add</button>
                                <button class="btn btn-default" type="submit" id="changeBtn" style="width:100px; height:34px;" onclick="location.href='@Url.Action("Add", "Function")'">Change</button>
                                <button class="btn btn-default" type="submit" id="deleteBtn" style="width:100px; height:34px;" onclick="location.href='@Url.Action("Add", "Function")'">Delete</button>
                            </div>

                        </div>
                    }
                </fieldset>

            </div>

            @*<div class="col-md-7">
                <fieldset>
                    <legend>
                        <a href="#" class="btn btn-primary btn-lg btn-block" style="background-color:#010431;">Company Name</a>
                    </legend>

                    <div class="container">
                        <div class="form-group">
                            <div class="row">
                                <label for="Exchange" class="col-md-3 control-label">Exchange</label>

                                <div class="col-md-3">
                                    <input type="text" class="form-control" id="ExchangeCode" placeholder="JSE">
                                </div>
                                <div class="col-md-5">
                                    <input type="text" class="form-control" id="ExchangeName" placeholder="JSE JSE STOCK EXCHANGE" />
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label for="Company Name" class="col-md-3 control-label">Company Name</label>
                                <div class="col-md-8">
                                    <input type="text" class="form-control" id="ExchangeCode">
                                </div>

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="ShortCode" class="col-md-3 control-label">Short Code (Ordinary)</label>
                                <div class="col-md-2">
                                    <input type="text" class="form-control" id="ExchangeCode" placeholder="BAW">
                                </div>
                                <label for="CompType" class="col-md-3 control-label">Company Type</label>
                                <div class="col-md-4">
                                    <select class="form-control" style="width:80%">
                                        <option class="Listed">Listed</option>
                                        <option class="Delisted">Delisted</option>
                                        <option class="Private">Private</option>
                                    </select>
                                </div>

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="Country" class="col-md-3 control-label">Country</label>
                                <div class="col-md-8">
                                    <input type="text" class="form-control" id="Country">
                                </div>

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="BusinessSector" class="col-md-3 control-label">Business Sector</label>
                                <div class="col-md-8">
                                    <input type="text" class="form-control" id="BusinessSector">
                                </div>

                            </div>
                        </div>
                    </div>
                    <br /><br /> <br /><br /><br /><br />  <br /><br /><br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <div class="form-inline form-group">
                        <div class="col-lg-10 col-lg-offset-3">
                            <button class="btn btn-default" type="submit" id="updateBtn" style="width:100px; height:34px;" onclick="location.href='@Url.Action("Add", "Function")'">Update</button>
                            <button class="btn btn-default" type="submit" id="exitBtn" style="width:100px; height:34px;" onClick="alert('Are you sure you want to exit?');location.href='@Url.Action("Login", "Home")'">Exit</button>
                            <button class="btn btn-default" type="submit" id="printBtn" style="width:100px; height:34px;" onclick="window.print();">Print Screen</button>
                        </div>*@

                    @*</div>

                </fieldset>
            </div>*@

        </div>


    </form>

</body>
</html>